name: publish-docker
on: pull_request

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'unicorn-985'
          credentials_json: ${{ secrets.GCE_NEW_TEST_JSON }}

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: unicorn-985

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud auth configure-docker europe-docker.pkg.dev

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "europe-docker.pkg.dev/unicorn-985/public-images/push-to-gcr-github-action:pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "europe-docker.pkg.dev/unicorn-985/public-images/push-to-gcr-github-action:pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}"
